### ISSUE TITLE
SSL Key file only readable by root fails

### ISSUE THREAD

**Issue by thenewguy** [docker-library/rabbitmq#283] opened 2018-10-12 16:30 UTC
My ssl key file is shared from the host with only root readable permissions.  The docker entrypoint script drops permissions before reading the ssl key file and fails.  Since you cannot run rabbitmq as root per https://github.com/docker-library/rabbitmq/issues/200 it would be nice if the ssl key file was read before dropping permissions

**Comment by yosifkit** [comment] 2018-10-12 18:11
Duplicate of https://github.com/docker-library/rabbitmq/issues/274
Duplicate of https://github.com/docker-library/rabbitmq/issues/59

See https://github.com/docker-library/rabbitmq/issues/59#issuecomment-413789875 for possible workarounds.

**Comment by thenewguy** [comment] 2018-10-12 18:32
Looks like that was my oops.  Whoops

Don't think that issue should have been closed.  Same problem. No resolution.  Simple to fix in the entrypoint script since it is initially run as root

**Comment by tianon** [comment] 2018-10-17 22:09
The contents of these files are pretty sensitive, so I'm not sure it's entirely reasonable to assume they're safe for us to copy willy-nilly somewhere else in our running container.  For example, this sort of issue is why Docker itself only supplies "secrets" to containers via an explicit `tmpfs` mount such that the secrets never end up unencrypted on-disk and live unencrypted only in-memory.

The existing `cat` into `/tmp/combined.pem` already makes me somewhat queasy and I'd love to find a better solution for that too.

**Comment by thenewguy** [comment] 2018-10-17 22:19
It's copied to a randomly named file that has readonly permissions set to the rabbitmq user.  I don't see how that is any less secure than passing a certificate the rabbitmq user can read except it is very difficult to do that in advance on the host and keep restrictive permissions.

I don't really see an alternative unless you allow the container to run rabbitmq as root.

**Closed** 2018-10-26 20:17 UTC
Labels: Request
