### ISSUE TITLE
docker pull rabbitmq:4.0-management-alpine is giving a manifest unknown error

### ISSUE THREAD

**Issue by easyjoh** [docker-library/rabbitmq#748] opened 2024-12-14 09:35 UTC
```
$ docker pull rabbitmq:4.0-management-alpine
4.0-management-alpine: Pulling from library/rabbitmq
manifest for rabbitmq:4.0-management-alpine not found: manifest unknown: manifest unknown
```

4.0.3 works:

```
$ docker pull rabbitmq:4.0.4-management-alpine
4.0.4-management-alpine: Pulling from library/rabbitmq
manifest for rabbitmq:4.0.4-management-alpine not found: manifest unknown: manifest unknown

$ docker pull rabbitmq:4.0.3-management-alpine
4.0.3-management-alpine: Pulling from library/rabbitmq
Digest: sha256:e4483ae83ec6491939c9b36397bd4c63a9667dffddd411a1698a5d01f9d54d50
Status: Downloaded newer image for rabbitmq:4.0.3-management-alpine
docker.io/library/rabbitmq:4.0.3-management-alpine
```

**Comment by dgarros** [comment] 2024-12-14 10:11
I'm seeing a similar issue for `rabbitmq:3.13.7-management` from MacOS M2 and from a linux server

```
docker pull rabbitmq:3.13.7-management
3.13.7-management: Pulling from library/rabbitmq
manifest for rabbitmq:3.13.7-management not found: manifest unknown: manifest unknown
```

**Comment by hawk9821** [comment] 2024-12-14 11:32
```
2024-12-14T11:08:14.6666046Z java.util.concurrent.CompletionException: org.testcontainers.containers.ContainerLaunchException: Container startup failed
2024-12-14T11:08:14.6667550Z Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
2024-12-14T11:08:14.6669836Z Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=rabbitmq:3.13.7-management, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$LogWrappedImageNameSubstitutor@3b2b6c00)
2024-12-14T11:08:14.6672677Z Caused by: org.testcontainers.containers.ContainerFetchException: Failed to get Docker client for rabbitmq:3.13.7-management
2024-12-14T11:08:14.6674364Z Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: manifest for rabbitmq:3.13.7-management not found: manifest unknown: manifest unknown
```
```
2024-12-14T10:40:14.6607035Z java.util.concurrent.CompletionException: org.testcontainers.containers.ContainerLaunchException: Container startup failed
2024-12-14T10:40:14.6608887Z Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
2024-12-14T10:40:14.6611411Z Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=rabbitmq:3-management, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$LogWrappedImageNameSubstitutor@5e2404d4)
2024-12-14T10:40:14.6613860Z Caused by: org.testcontainers.containers.ContainerFetchException: Failed to get Docker client for rabbitmq:3-management
2024-12-14T10:40:14.6615550Z Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: manifest for rabbitmq:3-management not found: manifest unknown: manifest unknown
```

**Comment by Enteee** [comment] 2024-12-14 12:16
pretty sure this is a duplicate of #747

**Comment by michaelklishin** [comment] 2024-12-14 17:03
I don't see how it is different from #747.

**Closed by michaelklishin** 2024-12-14 17:03 UTC

**Comment by thaJeztah** [comment] 2024-12-14 17:26
@michaelklishin In case you want to update on the other (locked) issues

(I work at Docker and am currently in a call with the team) this looks to be the same cause as the ticket below (for another repository); the team is actively working on this;

- https://github.com/docker-library/docker/issues/519

https://www.dockerstatus.com also has been updated to reflect the current status

**Comment by michaelklishin** [comment] 2024-12-14 17:53
@thaJeztah thank you very much for the update! And thank you to the team that is working a Saturday on-call shift, we really appreciate their help ❤️

**Comment by michaelklishin** [comment] 2024-12-14 18:46
``` shell
docker pull rabbitmq:3
```

``` shell
docker pull rabbitmq:3.13.7
```

both work for me now.

**Comment by kenylieou** [comment] 2024-12-18 11:47
I am still getting the error 

$ docker pull arm64v8/rabbitmq:4-management-alpine
4-management-alpine: Pulling from arm64v8/rabbitmq
failed to copy: httpReadSeeker: failed open: content at https://registry-1.docker.io/v2/arm64v8/rabbitmq/manifests/sha256:0e949cfbbb8a01e0d40da97621d58874fa0588bc8d433ccff30862a504dea9a9 not found: not found

**Comment by thaJeztah** [comment] 2024-12-18 11:53
@kenylieou thanks for porting; let me check with the team


cc @ jcarter3 @LaurentGoderre

**Comment by kenylieou** [comment] 2024-12-21 22:31
> docker pull arm64v8/rabbitmq:4-management-alpine

It works now, Thanks for your support.
