### ISSUE TITLE
latest only has i386 image

### ISSUE THREAD

**Issue by justincormack** [docker-library/rabbitmq#218] opened 2017-12-12 23:33 UTC
```
manifest-tool inspect library/rabbitmq:latest
Name:   library/rabbitmq:latest (Type: application/vnd.docker.distribution.manifest.list.v2+json)
Digest: sha256:ee9f21472e06a372761e46101d8ada27683984e78d581dece3209c5adadfc056
 * Contains 1 manifest references:
1    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
1       Digest: sha256:9454ef067d79274f94a8fe58047418a3172759ff4fa9815b4756449e89e62e73
1  Mfst Length: 2826
1     Platform:
1           -      OS: linux
1           - OS Vers: 
1           - OS Feat: []
1           -    Arch: 386
1           - Variant: 
1           - Feature: 
1     # Layers: 12
         layer 1: digest = sha256:4dbce982b05e209cf10a433462dc417f7816c47b0c1a151c8c93206b299b9a14
         layer 2: digest = sha256:2c7c11e0bc622b0180ed093c8a4da0dc404613fc4331a2436a3669aa08c6e818
         layer 3: digest = sha256:c6f7b212f68d587a5e50aa75b4635c7d49a9c744d221e091404cb2d1cf4327a1
         layer 4: digest = sha256:adb0df0b481030711e1f4ccd5b60509dc4796c769e4d46ddf668819aba41c5d2
         layer 5: digest = sha256:20e040f21d8962aea7005a7379e4852e408931ff4c1985b8debde30f1bcf14ca
         layer 6: digest = sha256:0c5bbc5be701d46339ee9aa060f79d61ef2ea60c0a862dc9663bac7b97a8e169
         layer 7: digest = sha256:74b6a22b1c298a7447a0383c535ef89874d89e40d6519f2a13a8fd431e079e88
         layer 8: digest = sha256:565c1d4f026ba3fb70bb0b0c7fef8d769396c1a199465dee3ea713ce72aa8018
         layer 9: digest = sha256:ffa1033d6bf863c3c23f85e731ecc752cfc001550f00ac5efdbdee227712466a
         layer 10: digest = sha256:22861ee8f8b6b22385b805bf492d9ec0bfc7ff97de4aabe26fe09c5871c1d681
         layer 11: digest = sha256:bea86f7d0f33a989f0952eac72705743f25c306ff2ad1fd6751073b60e296061
         layer 12: digest = sha256:d8228f21bc8091286bfb3945fb54b969af9858538a12a5eb6353680ab3e7f8b6
```

This means that `docker pull` fails on most machines:
```
docker pull rabbitmq
Using default tag: latest
latest: Pulling from library/rabbitmq
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by justincormack** [comment] 2017-12-12 23:34
cc @tianon

**Comment by tianon** [comment] 2017-12-12 23:34
Duplicate of https://github.com/docker-library/rabbitmq/issues/217.

**Closed by tianon** 2017-12-12 23:34 UTC
