### ISSUE TITLE
docker pull rabbitmq:3.13 is giving a manifest unknown error

### ISSUE THREAD

**Issue by gregsmith-vasion** [docker-library/rabbitmq#747] opened 2024-12-14 06:26 UTC
There was a push to Docker Hub at Dec 13, 2024 at 11:52 pm (US Eastern)...

```
docker pull rabbitmq:3.13                           
3.13: Pulling from library/rabbitmq
manifest for rabbitmq:3.13 not found: manifest unknown: manifest unknown
```

Any ideas what's going on here? Pulling `rabbitmq:4` and even `rabbitmq:3.13.6` works fine.

**Comment by mkniazuk123** [comment] 2024-12-14 07:39
`docker pull rabbitmq:3` also does not work

**Comment by vicolby** [comment] 2024-12-14 08:14
`rabbitmq:3-management not found` also

**Comment by gregsmith-vasion** [comment] 2024-12-14 08:15
I have a feeling 3.13.7 was recently introduced and something went wrong.

**Comment by knutster** [comment] 2024-12-14 09:15
Same here, had to revert to `3.13.6`. Will teach me not to use ranges.

**Comment by dimadeush** [comment] 2024-12-14 11:20
but 4.0.4 it seems working now. Please check 3.* versions.

**Comment by Enteee** [comment] 2024-12-14 12:17
same issue for `docker pull rabbitmq:3.13.7-management-alpine`

**Comment by JuanxCursed** [comment] 2024-12-14 14:21
+1 same issue here

**Comment by rockit666** [comment] 2024-12-14 16:37
Help please
![image](https://github.com/user-attachments/assets/9ae79e99-e3c1-409a-8b70-4d2ae9b9dbd3)

**Comment by michaelklishin** [comment] 2024-12-14 17:06
@tianon @yosifkit this cloud have something to do with the OS bump for both Alpine https://github.com/docker-library/rabbitmq/commit/0584c9d30e14c060a7fb677c5134f03da0d6a68d and Ubuntu 24.04 (specifically for `3.13.x`) https://github.com/docker-library/rabbitmq/pull/746 recently. Or just an infrastructure issue of sorts, because image updates usually do not affect older tags.

Do you folks know what may be going on?

**Comment by rockit666** [comment] 2024-12-14 17:18
Sorry, I have no clue. It's weird

**Comment by michaelklishin** [comment] 2024-12-14 17:18
> I have a feeling 3.13.7 was recently introduced and something went wrong

`3.13.7` is from [late August 2024](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.13.7).

While I won't pretend I know what may be going on but something that did happen recently was a major rebuilt after two OS updates mentioned above.

`3.13.7` is the only affected tag according to a quick `docker pull` test on two different hosts. `4.0.4` is perfectly fine.

For many environments, this may be a good moment to move to `4.x`, [the only community supported series](https://www.rabbitmq.com/release-information).

**Comment by michaelklishin** [comment] 2024-12-14 17:22
I don't think we need any more +1s or questions as to what may be going on. Now we have to wait for the maintainers and/or Docker Hub infrastructure folks find what's going on and rebuild, republish `3.13.7`. That won't happy any sooner if a few more speculative comments or +1s were posted.

We did establish that only the `3.13.7` tag is affected. `4.0.4` or `3.13.6` are fine. Switching to `4.0.4` where possible is what I'd recommend.

**Comment by michaelklishin** [comment] 2024-12-14 17:59
We have an update from a Docker, Inc team.

The issue is not entirely specific to this image. Please see [1][2].

There is an ongoing technical operations call, so the issue is not being ignored, quite the contrary.

1. https://www.dockerstatus.com/
2. https://github.com/docker-library/docker/issues/519

**Comment by LaurentGoderre** [comment] 2024-12-14 17:59
Closing in favor of the issue mentioned above.

**Closed** 2024-12-14 17:59 UTC

**Comment by michaelklishin** [comment] 2024-12-14 18:47
``` shell
docker pull rabbitmq:3
```

``` shell
docker pull rabbitmq:3.13.7
```

both work for me now.
