### ISSUE TITLE
Setting environment variables for default vhost, user, pass causes rabbitmq to crash on startup

### ISSUE THREAD

**Issue by dsaborg** [docker-library/rabbitmq#127] opened 2016-12-21 15:52 UTC
When I set environment variables for rabbitmq's default vhost, user or password it crashes on startup.

> sensu-rabbitmq_1  | /usr/local/bin/docker-entrypoint.sh: line 262: /etc/rabbitmq/rabbitmq.config: Permission denied
> sensu-rabbitmq_1 exited with code 1

I've set the variables in docker-compose.yml like so:

```
services:
  ...
  sensu-rabbitmq:
    ...
    environment:
      RABBITMQ_DEFAULT_VHOST: vhost
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: secret
```

Versions:

- Docker version 1.12.1, build 23cf638
- docker-compose version 1.9.0, build 2585387
- Running on Ubuntu 16.10

Note, this all works if you remove all three environment variables from docker-compose.

**Comment by tianon** [comment] 2016-12-21 22:34
I can't seem to reproduce this failure. :disappointed:
```console
$ docker pull rabbitmq
Using default tag: latest
latest: Pulling from library/rabbitmq

Digest: sha256:53c67c41323977870ad077c8a0e5ef52b2cc460206e6a965ced96ea130de1e12
Status: Image is up to date for rabbitmq:latest
$ docker run -it --rm --name test -e RABBITMQ_DEFAULT_VHOST=vhost -e RABBITMQ_DEFAULT_USER=user -e RABBITMQ_DEFAULT_PASS=secret rabbitmq

              RabbitMQ 3.6.6. Copyright (C) 2007-2016 Pivotal Software, Inc.
  ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
  ##  ##
  ##########  Logs: tty
  ######  ##        tty
  ##########
              Starting broker...

=INFO REPORT==== 21-Dec-2016::22:33:49 ===
Starting RabbitMQ 3.6.6 on Erlang 19.0
Copyright (C) 2007-2016 Pivotal Software, Inc.
Licensed under the MPL.  See http://www.rabbitmq.com/

=INFO REPORT==== 21-Dec-2016::22:33:49 ===
node           : rabbit@c95241f0c15f
home dir       : /var/lib/rabbitmq
config file(s) : /etc/rabbitmq/rabbitmq.config
cookie hash    : OUN0HrQuSd29W4J6jYjN6g==
log            : tty
sasl log       : tty
database dir   : /var/lib/rabbitmq/mnesia/rabbit@c95241f0c15f

=INFO REPORT==== 21-Dec-2016::22:33:50 ===
Memory limit set to 12859MB of 32148MB total.

=INFO REPORT==== 21-Dec-2016::22:33:50 ===
Disk free limit set to 50MB

=INFO REPORT==== 21-Dec-2016::22:33:50 ===
Limiting to approx 1048476 file handles (943626 sockets)

=INFO REPORT==== 21-Dec-2016::22:33:50 ===
FHC read buffering:  OFF
FHC write buffering: ON

=INFO REPORT==== 21-Dec-2016::22:33:51 ===
Database directory at /var/lib/rabbitmq/mnesia/rabbit@c95241f0c15f is empty. Initialising from scratch...

=INFO REPORT==== 21-Dec-2016::22:33:51 ===
    application: mnesia
    exited: stopped
    type: temporary

=INFO REPORT==== 21-Dec-2016::22:33:51 ===
Priority queues enabled, real BQ is rabbit_variable_queue

=INFO REPORT==== 21-Dec-2016::22:33:51 ===
Starting rabbit_node_monitor

=INFO REPORT==== 21-Dec-2016::22:33:51 ===
Adding vhost 'vhost'

=INFO REPORT==== 21-Dec-2016::22:33:51 ===
Creating user 'user'

=INFO REPORT==== 21-Dec-2016::22:33:51 ===
Setting user tags for user 'user' to [administrator]

=INFO REPORT==== 21-Dec-2016::22:33:51 ===
Setting permissions for 'user' in 'vhost' to '.*', '.*', '.*'

=INFO REPORT==== 21-Dec-2016::22:33:51 ===
msg_store_transient: using rabbit_msg_store_ets_index to provide index

=INFO REPORT==== 21-Dec-2016::22:33:51 ===
msg_store_persistent: using rabbit_msg_store_ets_index to provide index

=WARNING REPORT==== 21-Dec-2016::22:33:51 ===
msg_store_persistent: rebuilding indices from scratch

=INFO REPORT==== 21-Dec-2016::22:33:51 ===
started TCP Listener on [::]:5672
 completed with 0 plugins.

=INFO REPORT==== 21-Dec-2016::22:33:51 ===
Server startup complete; 0 plugins started.
```

**Comment by d2aborg** [comment] 2016-12-22 08:04
This only happens if you have an existing config in /etc/rabbitmq/rabbitmq.config, in which case the environment variable setup fails. It might be good if it failed with a more descriptive error message in this case.

**Comment by relicmelex** [comment] 2018-04-15 17:54
@tianon try using docker-compose.
This is where the failure comes in... :/
My Config file has some settings in it, but I'm not going to hard-code my username and password, and I'm also not going to write a manager for my containers since there's already a great one out there managed by docker. I'm hoping I can spur this for re-investigation as it'd be nice to have a config file and be able to set my username and password as the environment spins up and is different per environment but the rest of the config remains.

Cheers!

**Comment by tianon** [comment] 2018-04-24 20:59
With 3.7, this has been fixed via the new configuration file syntax which is trivial for us to append to. :+1:

**Closed by tianon** 2018-04-24 20:59 UTC
