### ISSUE TITLE
clustering: erlang cookie ownership

### ISSUE THREAD

**Issue by KeithWoods** [docker-library/rabbitmq#114] opened 2016-10-13 20:47 UTC
I'm trying to get clustering working and noticed I was getting this error on the node that first ran the cluster operation:

```
rabbit2_1  | start_error
rabbit2_1  | {"Error when reading /var/lib/rabbitmq/.erlang.cookie: eacces",[{auth,init_cookie,0,[{file,"auth.erl"},{line,286}]},{auth,init,1,[{file,"auth.erl"},{line,140}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
rabbit2_1  | [{pid,undefined},{id,auth},{mfargs,{auth,start_link,[]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]
rabbit2_1  | {local,kernel_sup}
```

my script is doing this:

```
/usr/sbin/rabbitmq-server -detached
rabbitmqctl stop_app
rabbitmqctl join_cluster rabbit@$someNode
```

If I add in the below before I interact with rabbit it seems to work fine. 

```
chown rabbitmq:rabbitmq /var/lib/rabbitmq/.erlang.cookie
```

Should the above `chown` be under this line? 
https://github.com/docker-library/rabbitmq/blob/29121864d4892b2481706df023a53e31fececd02/docker-entrypoint.sh#L139

**Comment by yosifkit** [comment] 2016-10-13 21:29
It shouldn't be needed (and indeed would fail), since we are running as the `rabbitmq` user (or another non-root user if `--user` was used on the docker run) after the `gosu` on [line  9](https://github.com/docker-library/rabbitmq/blob/29121864d4892b2481706df023a53e31fececd02/docker-entrypoint.sh#L9).

**Comment by KeithWoods** [comment] 2016-10-15 22:36
Thanks for the reply. Given my behaviour this isn't expected let me try recreate the steps and report back else this can be closed.

**Comment by seirdb** [comment] 2017-10-11 13:42
I've had some occasional crashes with my rabbitmq container with the same error message.
If I run the following command, it sometimes raises this issue (after about 50 tries or so)

`docker run -d --hostname rabbit --name rabbitmq-host -p 8080:15672 -p 5672:5672 rabbitmq:3.6.12-management && docker exec -i rabbitmq-host rabbitmqctl wait /var/lib/rabbitmq/mnesia/rabbit@rabbit.pid`

If I reboot the host the containers are running on, it _always_ results in a crashing container for the first time the command is executed.

My guess is that the daemonized container returns and then quickly the host tries to `docker exec` the rabbitmqctl command, which runs against the container daemon not having been able to update the permissions on the cookie?

**Comment by seirdb** [comment] 2017-10-11 14:08
Btw, adding `--user rabbitmq` to both run and exec seems to work as expected and doesn't crash the container.

**Comment by tianon** [comment] 2018-04-24 21:14
Closing given that this appears to be resolved and/or environmental.  If this can be reproduced, a new issue outlining the exact steps we can take to reproduce would be grand.  Thanks!

**Closed by tianon** 2018-04-24 21:14 UTC
