### ISSUE TITLE
Can't run rabbitmq:management-alpine  on  macbook  m1 cpu

### ISSUE THREAD

**Issue by Johnandfu** [docker-library/rabbitmq#478] opened 2021-04-09 08:48 UTC
it can't start in macbook  with m1 cpu，When I get into shell  operation rabbitmq-server, it's normal！

**Comment by wglambert** [comment] 2021-04-09 15:45
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

**Comment by Johnandfu** [comment] 2021-04-10 02:20
> Can you give all the commands you ran and any relevant files or logs for reproducing the issue

this no logs, where i run in docker for windows ,it's start up ,but i run in macbook with m1 cpu ,i must run docker-compose exec rabbitmq sh ,then input rabbit-server,it can start up

**Comment by wglambert** [comment] 2021-04-13 16:31
There's nothing in `docker logs` for the error?

I'd try asking or searching over at the [Docker for Mac](https://github.com/docker/for-mac/issues) repo

**Comment by Johnandfu** [comment] 2021-04-14 08:29
> There's nothing in `docker logs` for the error?
> 
> I'd try asking or searching over at the [Docker for Mac](https://github.com/docker/for-mac/issues) repo
thinks，I use in laradock，when I delete  privileged: true from docker-compose.yal,it start up now.

**Comment by Johnandfu** [comment] 2021-04-14 08:31
> There's nothing in `docker logs` for the error?
> 
> I'd try asking or searching over at the [Docker for Mac](https://github.com/docker/for-mac/issues) repo

thinks，I use in laradock，when I delete privileged: true from docker-compose.yal,it start up now.

**Comment by wglambert** [comment] 2021-04-14 16:22
Cool, closing since this is resolved then

**Closed by wglambert** 2021-04-14 16:22 UTC
Labels: question
