### ISSUE TITLE
Management plugin floods log with errors

### ISSUE THREAD

**Issue by jangrewe** [docker-library/rabbitmq#253] opened 2018-04-30 14:24 UTC
We have a 3 node cluster running the tag `3.7.4-management`, and those nodes are slowly but surely filling disks by logging errors caused by the the management plugin:
```
2018-04-30 14:18:07.061 [info] <0.33.0> Application lager started on node 'rabbit@clu-1-b'
2018-04-30 14:18:08.442 [info] <0.33.0> Application mnesia started on node 'rabbit@clu-1-b'
2018-04-30 14:18:08.444 [info] <0.33.0> Application mnesia exited with reason: stopped
2018-04-30 14:18:08.636 [info] <0.33.0> Application mnesia started on node 'rabbit@clu-1-b'
2018-04-30 14:18:08.636 [info] <0.33.0> Application recon started on node 'rabbit@clu-1-b'
2018-04-30 14:18:08.636 [info] <0.33.0> Application jsx started on node 'rabbit@clu-1-b'
2018-04-30 14:18:08.636 [info] <0.33.0> Application os_mon started on node 'rabbit@clu-1-b'
2018-04-30 14:18:08.636 [info] <0.33.0> Application xmerl started on node 'rabbit@clu-1-b'
2018-04-30 14:18:08.637 [info] <0.33.0> Application inets started on node 'rabbit@clu-1-b'
2018-04-30 14:18:08.637 [info] <0.33.0> Application asn1 started on node 'rabbit@clu-1-b'
2018-04-30 14:18:08.637 [info] <0.33.0> Application crypto started on node 'rabbit@clu-1-b'
2018-04-30 14:18:08.637 [info] <0.33.0> Application public_key started on node 'rabbit@clu-1-b'
2018-04-30 14:18:08.637 [info] <0.33.0> Application cowlib started on node 'rabbit@clu-1-b'
2018-04-30 14:18:08.637 [info] <0.33.0> Application ssl started on node 'rabbit@clu-1-b'
2018-04-30 14:18:08.637 [info] <0.33.0> Application ranch started on node 'rabbit@clu-1-b'
2018-04-30 14:18:08.641 [info] <0.33.0> Application cowboy started on node 'rabbit@clu-1-b'
2018-04-30 14:18:08.641 [info] <0.33.0> Application ranch_proxy_protocol started on node 'rabbit@clu-1-b'
2018-04-30 14:18:08.641 [info] <0.33.0> Application rabbit_common started on node 'rabbit@clu-1-b'
2018-04-30 14:18:08.643 [info] <0.33.0> Application amqp_client started on node 'rabbit@clu-1-b'
2018-04-30 14:18:08.643 [info] <0.251.0> 
 Starting RabbitMQ 3.7.4 on Erlang 20.2.4
 Copyright (C) 2007-2018 Pivotal Software, Inc.
 Licensed under the MPL.  See http://www.rabbitmq.com/

  ##  ##
  ##  ##      RabbitMQ 3.7.4. Copyright (C) 2007-2018 Pivotal Software, Inc.
  ##########  Licensed under the MPL.  See http://www.rabbitmq.com/
  ######  ##
  ##########  Logs: <stdout>

              Starting broker...
2018-04-30 14:18:08.644 [info] <0.251.0> 
 node           : rabbit@clu-1-b
 home dir       : /var/lib/rabbitmq
 config file(s) : /etc/rabbitmq/rabbitmq.conf
 cookie hash    : 0xnope...
 log(s)         : <stdout>
 database dir   : /var/lib/rabbitmq/mnesia/rabbit@clu-1-b
2018-04-30 14:18:08.855 [info] <0.331.0> Memory high watermark set to 51532 MiB (54036024524 bytes) of 128831 MiB (135090061312 bytes) total
2018-04-30 14:18:08.859 [info] <0.333.0> Enabling free disk space monitoring
2018-04-30 14:18:08.859 [info] <0.333.0> Disk free limit set to 50MB
2018-04-30 14:18:08.863 [info] <0.336.0> FHC read buffering:  OFF
2018-04-30 14:18:08.863 [info] <0.336.0> FHC write buffering: ON
2018-04-30 14:18:08.863 [info] <0.335.0> Limiting to approx 1048476 file handles (943626 sockets)
2018-04-30 14:18:08.866 [info] <0.251.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
2018-04-30 14:18:08.867 [info] <0.251.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
2018-04-30 14:18:08.911 [info] <0.251.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
2018-04-30 14:18:08.911 [info] <0.251.0> Peer discovery backend rabbit_peer_discovery_classic_config does not support registration, skipping registration.
2018-04-30 14:18:08.912 [info] <0.251.0> Priority queues enabled, real BQ is rabbit_variable_queue
2018-04-30 14:18:08.917 [info] <0.389.0> Starting rabbit_node_monitor
2018-04-30 14:18:08.939 [info] <0.251.0> Management plugin: using rates mode 'basic'
2018-04-30 14:18:08.939 [info] <0.415.0> Making sure data directory '/var/lib/rabbitmq/mnesia/rabbit@clu-1-b/msg_stores/vhosts/628WB79CIFDYO9LJI6DKMI09L' for vhost '/' exists
2018-04-30 14:18:08.941 [info] <0.415.0> Starting message stores for vhost '/'
2018-04-30 14:18:08.941 [info] <0.419.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_transient": using rabbit_msg_store_ets_index to provide index
2018-04-30 14:18:08.943 [info] <0.415.0> Started message store of type transient for vhost '/'
2018-04-30 14:18:08.943 [info] <0.422.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent": using rabbit_msg_store_ets_index to provide index
2018-04-30 14:18:08.945 [info] <0.415.0> Started message store of type persistent for vhost '/'
2018-04-30 14:18:08.996 [info] <0.535.0> Making sure data directory '/var/lib/rabbitmq/mnesia/rabbit@clu-1-b/msg_stores/vhosts/CPZYVZ8FXM414K16J269JBK6V' for vhost 'prod' exists
2018-04-30 14:18:08.998 [info] <0.535.0> Starting message stores for vhost 'prod'
2018-04-30 14:18:08.998 [info] <0.539.0> Message store "CPZYVZ8FXM414K16J269JBK6V/msg_store_transient": using rabbit_msg_store_ets_index to provide index
2018-04-30 14:18:09.000 [info] <0.535.0> Started message store of type transient for vhost 'prod'
2018-04-30 14:18:09.000 [info] <0.542.0> Message store "CPZYVZ8FXM414K16J269JBK6V/msg_store_persistent": using rabbit_msg_store_ets_index to provide index
2018-04-30 14:18:09.001 [info] <0.535.0> Started message store of type persistent for vhost 'prod'
2018-04-30 14:18:09.070 [info] <0.703.0> started TCP Listener on [::]:5672
2018-04-30 14:18:09.072 [info] <0.251.0> Setting up a table for connection tracking on this node: 'tracked_connection_on_node_rabbit@clu-1-b'
2018-04-30 14:18:09.073 [info] <0.251.0> Setting up a table for per-vhost connection counting on this node: 'tracked_connection_per_vhost_on_node_rabbit@clu-1-b'
2018-04-30 14:18:09.074 [info] <0.389.0> rabbit on node 'rabbit@clu-2-b' up
2018-04-30 14:18:09.074 [info] <0.33.0> Application rabbit started on node 'rabbit@clu-1-b'
2018-04-30 14:18:09.097 [info] <0.389.0> rabbit on node 'rabbit@clu-3-b' up
2018-04-30 14:18:09.108 [info] <0.33.0> Application rabbitmq_management_agent started on node 'rabbit@clu-1-b'
2018-04-30 14:18:09.108 [info] <0.33.0> Application rabbitmq_web_dispatch started on node 'rabbit@clu-1-b'
2018-04-30 14:18:09.153 [info] <0.756.0> Management plugin started. Port: 15672
2018-04-30 14:18:09.153 [info] <0.862.0> Statistics database started.
2018-04-30 14:18:09.154 [info] <0.33.0> Application rabbitmq_management started on node 'rabbit@clu-1-b'
 completed with 3 plugins.
2018-04-30 14:18:09.318 [info] <0.5.0> Server startup complete; 3 plugins started.
 * rabbitmq_management
 * rabbitmq_web_dispatch
 * rabbitmq_management_agent
2018-04-30 14:18:09.762 [error] <0.883.0> CRASH REPORT Process <0.883.0> with 0 neighbours crashed with reason: bad argument in call to erlang:port_get_data(#Port<0.25771>) in prim_file:sendfile/8
2018-04-30 14:18:09.762 [error] <0.758.0> Ranch listener rabbit_web_dispatch_sup_15672 had connection process started with cowboy_clear:start_link/4 at <0.883.0> exit with reason: {badarg,[{erlang,port_get_data,[#Port<0.25771>],[]},{prim_file,sendfile,8,[]},{file,sendfile,8,[{file,"file.erl"},{line,1287}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,161}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,148}]},{cowboy_http,commands,3,[{file,"src/cowboy_http.erl"},{line,982}]},{cowboy_http,loop,2,[{file,"src/cowboy_http.erl"},{line,200}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-04-30 14:18:11.745 [error] <0.890.0> CRASH REPORT Process <0.890.0> with 0 neighbours crashed with reason: bad argument in call to erlang:port_get_data(#Port<0.25779>) in prim_file:sendfile/8
2018-04-30 14:18:11.745 [error] <0.758.0> Ranch listener rabbit_web_dispatch_sup_15672 had connection process started with cowboy_clear:start_link/4 at <0.890.0> exit with reason: {badarg,[{erlang,port_get_data,[#Port<0.25779>],[]},{prim_file,sendfile,8,[]},{file,sendfile,8,[{file,"file.erl"},{line,1287}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,161}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,148}]},{cowboy_http,commands,3,[{file,"src/cowboy_http.erl"},{line,982}]},{cowboy_http,loop,2,[{file,"src/cowboy_http.erl"},{line,200}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-04-30 14:18:11.757 [error] <0.898.0> CRASH REPORT Process <0.898.0> with 0 neighbours crashed with reason: bad argument in call to erlang:port_get_data(#Port<0.25787>) in prim_file:sendfile/8
2018-04-30 14:18:11.758 [error] <0.758.0> Ranch listener rabbit_web_dispatch_sup_15672 had connection process started with cowboy_clear:start_link/4 at <0.898.0> exit with reason: {badarg,[{erlang,port_get_data,[#Port<0.25787>],[]},{prim_file,sendfile,8,[]},{file,sendfile,8,[{file,"file.erl"},{line,1287}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,161}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,148}]},{cowboy_http,commands,3,[{file,"src/cowboy_http.erl"},{line,982}]},{cowboy_http,loop,2,[{file,"src/cowboy_http.erl"},{line,200}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-04-30 14:18:11.770 [error] <0.904.0> CRASH REPORT Process <0.904.0> with 0 neighbours crashed with reason: no match of right hand value {error,einval} in prim_file:sendfile/8
2018-04-30 14:18:11.771 [error] <0.758.0> Ranch listener rabbit_web_dispatch_sup_15672 had connection process started with cowboy_clear:start_link/4 at <0.904.0> exit with reason: {{badmatch,{error,einval}},[{prim_file,sendfile,8,[]},{file,sendfile,8,[{file,"file.erl"},{line,1287}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,161}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,148}]},{cowboy_http,commands,3,[{file,"src/cowboy_http.erl"},{line,982}]},{cowboy_http,loop,2,[{file,"src/cowboy_http.erl"},{line,200}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-04-30 14:18:13.748 [error] <0.910.0> CRASH REPORT Process <0.910.0> with 0 neighbours crashed with reason: bad argument in call to erlang:port_get_data(#Port<0.25801>) in prim_file:sendfile/8
2018-04-30 14:18:13.749 [error] <0.758.0> Ranch listener rabbit_web_dispatch_sup_15672 had connection process started with cowboy_clear:start_link/4 at <0.910.0> exit with reason: {badarg,[{erlang,port_get_data,[#Port<0.25801>],[]},{prim_file,sendfile,8,[]},{file,sendfile,8,[{file,"file.erl"},{line,1287}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,161}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,148}]},{cowboy_http,commands,3,[{file,"src/cowboy_http.erl"},{line,982}]},{cowboy_http,loop,2,[{file,"src/cowboy_http.erl"},{line,200}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-04-30 14:18:13.754 [error] <0.914.0> CRASH REPORT Process <0.914.0> with 0 neighbours crashed with reason: no match of right hand value {error,einval} in prim_file:sendfile/8
2018-04-30 14:18:13.754 [error] <0.758.0> Ranch listener rabbit_web_dispatch_sup_15672 had connection process started with cowboy_clear:start_link/4 at <0.914.0> exit with reason: {{badmatch,{error,einval}},[{prim_file,sendfile,8,[]},{file,sendfile,8,[{file,"file.erl"},{line,1287}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,161}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,148}]},{cowboy_http,commands,3,[{file,"src/cowboy_http.erl"},{line,982}]},{cowboy_http,loop,2,[{file,"src/cowboy_http.erl"},{line,200}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-04-30 14:18:13.759 [error] <0.916.0> CRASH REPORT Process <0.916.0> with 0 neighbours crashed with reason: no match of right hand value {error,einval} in prim_file:sendfile/8
2018-04-30 14:18:13.760 [error] <0.758.0> Ranch listener rabbit_web_dispatch_sup_15672 had connection process started with cowboy_clear:start_link/4 at <0.916.0> exit with reason: {{badmatch,{error,einval}},[{prim_file,sendfile,8,[]},{file,sendfile,8,[{file,"file.erl"},{line,1287}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,161}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,148}]},{cowboy_http,commands,3,[{file,"src/cowboy_http.erl"},{line,982}]},{cowboy_http,loop,2,[{file,"src/cowboy_http.erl"},{line,200}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-04-30 14:18:13.764 [error] <0.920.0> CRASH REPORT Process <0.920.0> with 0 neighbours crashed with reason: no match of right hand value {error,einval} in prim_file:sendfile/8
2018-04-30 14:18:13.764 [error] <0.758.0> Ranch listener rabbit_web_dispatch_sup_15672 had connection process started with cowboy_clear:start_link/4 at <0.920.0> exit with reason: {{badmatch,{error,einval}},[{prim_file,sendfile,8,[]},{file,sendfile,8,[{file,"file.erl"},{line,1287}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,161}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,148}]},{cowboy_http,commands,3,[{file,"src/cowboy_http.erl"},{line,982}]},{cowboy_http,loop,2,[{file,"src/cowboy_http.erl"},{line,200}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-04-30 14:18:13.771 [error] <0.922.0> CRASH REPORT Process <0.922.0> with 0 neighbours crashed with reason: no match of right hand value {error,einval} in prim_file:sendfile/8
2018-04-30 14:18:13.772 [error] <0.758.0> Ranch listener rabbit_web_dispatch_sup_15672 had connection process started with cowboy_clear:start_link/4 at <0.922.0> exit with reason: {{badmatch,{error,einval}},[{prim_file,sendfile,8,[]},{file,sendfile,8,[{file,"file.erl"},{line,1287}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,161}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,148}]},{cowboy_http,commands,3,[{file,"src/cowboy_http.erl"},{line,982}]},{cowboy_http,loop,2,[{file,"src/cowboy_http.erl"},{line,200}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-04-30 14:18:15.743 [error] <0.924.0> CRASH REPORT Process <0.924.0> with 0 neighbours crashed with reason: bad argument in call to erlang:port_get_data(#Port<0.25818>) in prim_file:sendfile/8
2018-04-30 14:18:15.743 [error] <0.758.0> Ranch listener rabbit_web_dispatch_sup_15672 had connection process started with cowboy_clear:start_link/4 at <0.924.0> exit with reason: {badarg,[{erlang,port_get_data,[#Port<0.25818>],[]},{prim_file,sendfile,8,[]},{file,sendfile,8,[{file,"file.erl"},{line,1287}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,161}]},{ranch_tcp,sendfile,5,[{file,"src/ranch_tcp.erl"},{line,148}]},{cowboy_http,commands,3,[{file,"src/cowboy_http.erl"},{line,982}]},{cowboy_http,loop,2,[{file,"src/cowboy_http.erl"},{line,200}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
[...]
```

The management interface seems to work fine nonetheless, but the amount of errors just makes it a pain to have enabled.

Using the tag `3.7.4` stops these errors.

**Comment by tianon** [comment] 2018-04-30 17:06
I'm certainly not an expert, but the logs seem to imply that something in the management plugin is crashing.  Have you checked to ensure your system has enough RAM, etc to run the workload you're putting into your RabbitMQ instance?

I don't think we do anything very special in the `-management` image beyond simply enabling the management plugin, so I'm inclined to think this is probably an issue with either your environment or the management plugin itself (and thus not something we can fix in the Docker image).

**Comment by jangrewe** [comment] 2018-05-08 11:42
@tianon i was sent back here... https://github.com/rabbitmq/rabbitmq-management/issues/570#issuecomment-387374389

**Comment by michaelklishin** [comment] 2018-05-08 12:32
The error says that an HTTP server socket was in an `einval` state. Without a way to reliably reproduce  I dare to say it's very likely an environment-specific problem.

**Comment by michaelklishin** [comment] 2018-05-08 12:33
@essen have you seen anything like this reported for Cowboy or Ranch? I fail to come up with a hypothesis.

**Comment by michaelklishin** [comment] 2018-05-08 12:34
A fantastic source of information on this would be a Wireshark traffic capture.

**Comment by michaelklishin** [comment] 2018-05-08 13:31
It turns out the reason for this is proxy [TCP health checks](https://github.com/rabbitmq/rabbitmq-management/issues/570#issuecomment-387391469). Cowboy could handle this more gracefully or HTTP health checks could be used (assuming they are available in the proxy product in question).

**Comment by essen** [comment] 2018-05-08 15:16
I've seen occasionally errors in `prim_file:sendfile` but never this much. I guess Cowboy can guard against those by catching exceptions when they happen and terminating the connection (the socket seems to be gone already anyway).

In addition I wouldn't be against having an option to disable sendfile (and send via normal socket calls instead), as it has other issues when used with Virtualbox for example.

**Comment by yosifkit** [comment] 2018-05-08 19:12
Since this is an upstream issue and not something specific to the image, I'll close the issue here. You can follow the upstream issue over there: https://github.com/ninenines/cowboy/issues/1290.

Thanks to @essen and [matikij](https://github.com/rabbitmq/rabbitmq-management/issues/570#issuecomment-387391469) for looking into it!

**Closed by yosifkit** 2018-05-08 19:12 UTC
Labels: question
