### ISSUE TITLE
Adding RABBITMQ_CTL_ERL_ARGS when TLS

### ISSUE THREAD

**Issue by basz** [docker-library/rabbitmq#165] opened 2017-06-15 11:01 UTC
To have `rabbitmqctl` work with TLS I needed to add as an env var:

```
RABBITMQ_CTL_ERL_ARGS: "-proto_dist inet_tls"
```

That should be added to documentation or perhaps in the entry point.

**Comment by michaelklishin** [comment] 2017-06-15 13:10
👍

**Comment by artooro** [comment] 2017-08-24 21:09
Thanks @basz this was really helpful. Now I just need to figure out how to get MQTT to listen on TLS yet using this image.

**Comment by peterstory** [comment] 2018-01-26 18:53
That was incredibly helpful, thank you! I definitely agree, this should be mentioned more prominently in the documentation.

**Comment by artooro** [comment] 2018-01-26 23:01
For what it's worth, using the latest docker images I was able to configure TLS without having to add this. I've deployed rabbitmq 3.7 on kubernetes and it's been working really well.

**Comment by tianon** [comment] 2018-04-19 21:06
Cool, thanks @artooro!  Closing then!

**Closed by tianon** 2018-04-19 21:06 UTC

**Comment by mheese** [comment] 2018-06-28 19:19
@artooro I disagree, with the 3.7.6-management image at least, the `rabbitmqctl` tool still will not work when the mentioned `RABBITMQ_CTL_ERL_ARGS="-proto_dist inet_tls"` has not set.

I vote for updating the documentation and not just closing this @tianon 

to be clear on the issue:
- one can successfully configure TLS for both rabbitmq and the management plugin with the described documentation
- any execution of `rabbitmqctl` though inside the container will fail though ... a note about this on the documentation would be much appreciated

@basz thanks for opening this issue and adding the solution. that's a life saver!

**Comment by ramato-procon** [comment] 2018-08-16 07:26
I had the same issue. I think the problem is that in the entrypoint RABBITMQ_CTL_ERL_ARGS is set and exported. But the export only works for child processes. So you have to pass RABBITMQ_CTL_ERL_ARGS as environment variable. Or you can use the docker entrypoint:

> docker-entrypoint.sh rabbitmqctl status

**Comment by remort** [comment] 2019-05-26 17:10
I have the same issue even if `RABBITMQ_CTL_ERL_ARGS` is set inside a container.

```
root@92ffd5e7a77d:/# env|fgrep 'RABBITMQ_CTL_ERL_ARGS="-proto_dist inet_tls"'
RABBITMQ_CTL_ERL_ARGS="-proto_dist inet_tls"
```
