### ISSUE TITLE
When I pulled the latest version (57c6648d09d0) I got this error

### ISSUE THREAD

**Issue by hadasf** [docker-library/rabbitmq#147] opened 2017-04-09 12:02 UTC
```

=INFO REPORT==== 9-Apr-2017::11:42:03 ===
    application: mnesia
    exited: stopped
    type: temporary

=INFO REPORT==== 9-Apr-2017::11:42:03 ===
Error description:
   {could_not_start,rabbit,
       {error,
           {{shutdown,
                {failed_to_start_child,rabbit_memory_monitor,
                    {badarg,
                        [{lists,member,[disk,{error,bad_module}],[]},
                         {rabbit_memory_monitor,init,1,
                             [{file,"src/rabbit_memory_monitor.erl"},
                              {line,121}]},
                         {gen_server2,init_it,6,
                             [{file,"src/gen_server2.erl"},{line,554}]},
                         {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,247}]}]}}},
            {child,undefined,rabbit_memory_monitor_sup,
                {rabbit_restartable_sup,start_link,
                    [rabbit_memory_monitor_sup,
                     {rabbit_memory_monitor,start_link,[]},
                     false]},
                transient,infinity,supervisor,
                [rabbit_restartable_sup]}}}}

Log files (may contain more information):
   tty
   tty

{"init terminating in do_boot",{could_not_start,rabbit,{error,{{shutdown,{failed_to_start_child,rabbit_memory_monitor,{badarg,[{lists,member,[disk,{error,bad_module}],[]},{rabbit_memory_monitor,init,1,[{file,"src/rabbit_memory_monitor.erl"},{line,121}]},{gen_server2,init_it,6,[{file,"src/gen_server2.erl"},{line,554}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{child,undefined,rabbit_memory_monitor_sup,{rabbit_restartable_sup,start_link,[rabbit_memory_monitor_sup,{rabbit_memory_monitor,start_link,[]},false]},transient,infinity,supervisor,[rabbit_restartable_sup]}}}}}
init terminating in do_boot ()
```

**Comment by tsupertramp** [comment] 2017-04-10 10:01
Having the same issue.

**Comment by rvzanten** [comment] 2017-04-10 10:17
Same issue here. Please fix this.

**Comment by tianon** [comment] 2017-04-10 14:36
Can you please provide more information?  The exact "docker run" line,
system specs, and full logs would be helpful.

**Comment by mnussbaum** [comment] 2017-04-10 16:35
I'm seeing this as well, to reproduce:

```bash
docker pull rabbitmq:3-management
docker run  rabbitmq:3-management
```

Output from `docker version`:

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64
```

Full failure logs at https://gist.github.com/mnussbaum/36dd34131c851efdc93cd075a741b25f

**Comment by yosifkit** [comment] 2017-04-10 16:57
@mnussbaum, are you sure that you are setting no flags on `docker run`?  These lines in the logs seems suspicious: `Memory limit set to 0MB of 30210MB total.` and `vm_memory_high_watermark set. Memory used:64831856 allowed:0`.  Is that the same problem others here are seeing?

It works fine here: 
```console
$ docker run -d --name rabbit rabbitmq:3-management
93de73ce8b507e5ee1224698db9db902ac50b3b0fb2fae376d1e0e437b2c6344
$ docker logs rabbit

              RabbitMQ 3.6.9. Copyright (C) 2007-2016 Pivotal Software, Inc.
  ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
  ##  ##
  ##########  Logs: tty
  ######  ##        tty
  ##########
              Starting broker...

=INFO REPORT==== 10-Apr-2017::16:53:06 ===
Starting RabbitMQ 3.6.9 on Erlang 19.3
Copyright (C) 2007-2016 Pivotal Software, Inc.
Licensed under the MPL.  See http://www.rabbitmq.com/

=INFO REPORT==== 10-Apr-2017::16:53:06 ===
node           : rabbit@93de73ce8b50
home dir       : /var/lib/rabbitmq
config file(s) : /etc/rabbitmq/rabbitmq.config
cookie hash    : x683XlaBtI8Em8dKo+49iQ==
log            : tty
sasl log       : tty
database dir   : /var/lib/rabbitmq/mnesia/rabbit@93de73ce8b50

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
Memory limit set to 12646MB of 31615MB total.

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
Disk free limit set to 50MB

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
Limiting to approx 1048476 file handles (943626 sockets)

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
FHC read buffering:  OFF
FHC write buffering: ON

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
Database directory at /var/lib/rabbitmq/mnesia/rabbit@93de73ce8b50 is empty. Initialising from scratch...

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
    application: mnesia
    exited: stopped
    type: temporary

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
Waiting for Mnesia tables for 30000 ms, 9 retries left

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
Waiting for Mnesia tables for 30000 ms, 9 retries left

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
Waiting for Mnesia tables for 30000 ms, 9 retries left

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
Priority queues enabled, real BQ is rabbit_variable_queue

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
Starting rabbit_node_monitor

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
Management plugin: using rates mode 'basic'

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
msg_store_transient: using rabbit_msg_store_ets_index to provide index

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
msg_store_persistent: using rabbit_msg_store_ets_index to provide index

=WARNING REPORT==== 10-Apr-2017::16:53:07 ===
msg_store_persistent: rebuilding indices from scratch

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
Adding vhost '/'

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
Creating user 'guest'

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
Setting user tags for user 'guest' to [administrator]

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
Setting permissions for 'guest' in '/' to '.*', '.*', '.*'

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
started TCP Listener on [::]:5672

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
Management plugin started. Port: 15672

=INFO REPORT==== 10-Apr-2017::16:53:07 ===
Statistics database started.
 completed with 6 plugins.

=INFO REPORT==== 10-Apr-2017::16:53:08 ===
Server startup complete; 6 plugins started.
 * rabbitmq_management
 * rabbitmq_web_dispatch
 * rabbitmq_management_agent
 * amqp_client
 * cowboy
 * cowlib
```

**Comment by mnussbaum** [comment] 2017-04-10 17:39
@yosifkit yeah I'm running `docker run  rabbitmq:3-management` exactly, I'm not setting any memory limits. I suppose you pulled before you tested? This problem wasn't occurring for me last week, but is as of this Mon. morning.

**Comment by tianon** [comment] 2017-04-10 17:41
@mnussbaum you're not using any extra flags to `docker run`?  No `docker-compose` args?  Any other system in place that might be modifying the container startup in some way? (`docker version`, `docker info`, and `uname -a` would be helpful)

**Comment by mnussbaum** [comment] 2017-04-10 17:45
No other flags to `docker run`, not using `docker-compose`, and no other system in place modifying container startup.

Here's version/info you output:

```bash
$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64

$ docker info
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 96
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-791902-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.543 GB
 Data Space Total: 107.4 GB
 Data Space Available: 39.69 GB
 Metadata Space Used: 5.894 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.90 (2014-09-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 29.5 GiB
Name: ip-10-254-64-181
ID: 7DQ3:75X3:7CI7:DDBT:X6MO:7NPS:LUO6:2SRH:AYCD:QUFA:GNYS:2DS7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8

$ uname -a
Linux ip-10-254-64-181 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux
```

**Comment by yosifkit** [comment] 2017-04-10 18:14
Ugh, `WARNING: No kernel memory limit support`, why does the kernel then put `0` in the file? :cry:

**Comment by tianon** [comment] 2017-04-10 18:18
Just to be sure, can we get the output of "docker run --rm alpine
cat /sys/fs/cgroup/memory/memory.limit_in_bytes" ? (should be able to use
just about any image in place of "alpine" there)

**Comment by tianon** [comment] 2017-04-10 19:15
See also https://github.com/docker-library/rabbitmq/issues/149, which I believe will fix the issues being seen here.

**Comment by ddavidovic** [comment] 2017-04-11 13:38
I had the same problem with starting rabbitmq (3-management).
In my case the problem was in the version of Docker (1.12.2). After I upgraded docker to version 1.12.3 the problem simply disappear. 

Hope it helps!

**Comment by tianon** [comment] 2017-04-11 16:50
Can one of those who is getting `Memory limit set to 0MB ...` please give the full output of `docker run --rm cat /sys/fs/cgroup/memory/memory.limit_in_bytes /proc/meminfo` ?

I've got #149, but I can't reproduce whatever is causing `0MB` to be the detected value in the first place, so I want to check my assumptions. :cold_sweat:

**Comment by yosifkit** [comment] 2017-04-11 21:01
Fixed via https://github.com/docker-library/rabbitmq/pull/149. PR to official-images coming shortly.

**Closed by yosifkit** 2017-04-11 21:01 UTC
