### ISSUE TITLE
docker-entrypoint.sh: 56 -- /etc/rabblitmq/rabbitmq.config: Permission denied

### ISSUE THREAD

**Issue by derailed** [docker-library/rabbitmq#64] opened 2016-01-29 13:40 UTC
Hi,

    I am using the following image and getting this perm issue as soon as I setup a default USER/PASS in my environment. If I omit these env var all is well. Looks like perms 644 by root on rabbitmq.config which seems right.

   Guessing the file already exists and chokes on cat > vs cat >> at line 56?? as lookback_users, occurs later in the script and seems to get set correctly??

   image: rabbitmq:3.6.0-management

  What am I missing?

Thank you!!

**Comment by KNonen** [comment] 2016-01-29 17:14
I have this problem too.
image: rabbitmq:3.6

**Comment by tianon** [comment] 2016-01-29 17:21
Duplicate of #61 which was fixed by #62 and merged downstream in the library in https://github.com/docker-library/official-images/pull/1390 (which is currently building on the official server and will be pushed shortly).

**Comment by tianon** [comment] 2016-01-29 17:21
Sorry for the trouble!

**Closed by tianon** 2016-01-29 17:21 UTC

**Comment by derailed** [comment] 2016-01-29 18:36
Nw - Figured that was the issue as I pull and build local and all was
peachy...

Thank you for the prompt reply and awesome image!

-Fernand
