### ISSUE TITLE
Extending configuration generation

### ISSUE THREAD

**Issue by arteme** [docker-library/rabbitmq#324] opened 2019-03-04 13:53 UTC
It would be nice to be able to extend the configuration file generation when extending from this docker image. It would be nice to be able to add custom logic at the end of the configuration file generation.

Something along the line of (shamelessly stolen from postgresql docker container) this in `docker-entrypoint.sh`:
```
if [ "$1" = 'rabbitmq-server' ] && [ "$shouldWriteConfig" ]; then
                    # ....current logic....

                    echo
                    for f in /docker-entrypoint-initdb.d/*; do
                        case "$f" in
                                *.sh)
                                          echo "$0: sourcing $f"
                                          . "$f"
                                          ;;
                                *)        echo "$0: ignoring $f" ;;
                        esac
                        echo
                    done
fi
```

**Comment by yosifkit** [comment] 2019-03-05 00:18
Duplicate of #53, see the [final comment](https://github.com/docker-library/rabbitmq/pull/53#issuecomment-431517809).

I'd also say this is similar to #202 and similar issues. Especially this https://github.com/docker-library/rabbitmq/pull/202#issuecomment-337414006:

> Especially with 3.7's simpler config format, we'd rather move to doing less config via the entrypoint. Since it will be simpler for a user to supply their own config file and then the entrypoint can sed their file to update/add a limited set of specific values rather than being responsible for every option possible in a rabbit config.

Since the introduction of the 3.7 image, you can supply `/etc/rabbitmq/rabbitmq.conf` and the entrypoint will only add/sed supplied envs while leaving other lines in the file untouched (https://github.com/docker-library/rabbitmq/pull/197#issuecomment-350346234).

**Closed by yosifkit** 2019-03-05 00:18 UTC
Labels: Request

**Comment by arteme** [comment] 2019-03-05 08:36
Thank you, this is indeed enough for my use-case. The fact that `rabbitmq.conf` is appended escaped my attention when reading the entry-point script.
