### ISSUE TITLE
Conf file attempted to set unknown variable: total_memory_available_override_value

### ISSUE THREAD

**Issue by misgina** [docker-library/rabbitmq#235] opened 2018-02-07 10:56 UTC
Hi with the latest tag 3-management, we are experiencing a problem, rabbitmq failed to boot.

Here is the error logs.

Thanks.

```console
BOOT FAILED
===========

Config file generation failed 10:51:14.510 [error] You've tried to set total_memory_available_override_value, but there is no setting with that name.
10:51:14.510 [error]   Did you mean one of these?
10:51:14.529 [error]     memory_monitor_interval
10:51:14.529 [error]     vm_memory_calculation_strategy
10:51:14.529 [error]     vm_memory_high_watermark.absolute
10:51:14.530 [error] Error generating configuration in phase transform_datatypes
10:51:14.530 [error] Conf file attempted to set unknown variable: total_memory_available_override_value


BOOT FAILED
===========

Error description:
    rabbit:start_it/1 line 448
    rabbit:boot_error/2 line 848
    rabbit_lager:log_locations/0 line 59
    rabbit_lager:ensure_lager_configured/0 line 160
    rabbit_lager:lager_configured/0 line 167
    lager:list_all_sinks/0 line 317
    lager_config:get/2 line 71
    ets:lookup(lager_config, {'_global',handlers})
exit:generate_config_file
Log file(s) (may contain more information):

{"init terminating in do_boot",generate_config_file}
init terminating in do_boot (generate_config_file)

Crash dump is being written to: /var/log/rabbitmq/erl_crash.dump...done
```

**Comment by yosifkit** [comment] 2018-02-08 00:11
Duplicate of https://github.com/rabbitmq/rabbitmq-server/issues/1445. Please pull an updated image.

```console
$ docker pull rabbitmq:3-management
3-management: Pulling from library/rabbitmq
e7bb522d92ff: Pull complete 
ad90649c4d84: Pull complete 
5a318b914d6c: Pull complete 
cedd60f70052: Pull complete 
f4ec28761801: Pull complete 
b8fa44aa9074: Pull complete 
e8002a209c24: Pull complete 
cd1206edcd43: Pull complete 
769be0727074: Pull complete 
7308b93d35af: Pull complete 
c4102ef22c29: Pull complete 
fefc8e1aa4b5: Pull complete 
a271d400045b: Pull complete 
b0d4c40c62de: Pull complete 
Digest: sha256:ce1f6f597861a0e11942ad30415b192379a69b491a5899eead98abcf88430e31
Status: Downloaded newer image for rabbitmq:3-management
$ docker run -it --rm -m 500m rabbitmq:3-management
2018-02-08 00:07:11.347 [info] <0.33.0> Application lager started on node rabbit@f82e877572f0
2018-02-08 00:07:11.832 [info] <0.33.0> Application mnesia started on node rabbit@f82e877572f0
2018-02-08 00:07:11.900 [info] <0.33.0> Application inets started on node rabbit@f82e877572f0
2018-02-08 00:07:11.900 [info] <0.33.0> Application recon started on node rabbit@f82e877572f0
2018-02-08 00:07:11.905 [info] <0.33.0> Application os_mon started on node rabbit@f82e877572f0
2018-02-08 00:07:11.905 [info] <0.33.0> Application crypto started on node rabbit@f82e877572f0
2018-02-08 00:07:11.905 [info] <0.33.0> Application cowlib started on node rabbit@f82e877572f0
2018-02-08 00:07:11.905 [info] <0.33.0> Application jsx started on node rabbit@f82e877572f0
2018-02-08 00:07:11.905 [info] <0.33.0> Application xmerl started on node rabbit@f82e877572f0
2018-02-08 00:07:11.905 [info] <0.33.0> Application asn1 started on node rabbit@f82e877572f0
2018-02-08 00:07:11.905 [info] <0.33.0> Application public_key started on node rabbit@f82e877572f0
2018-02-08 00:07:11.964 [info] <0.33.0> Application ssl started on node rabbit@f82e877572f0
2018-02-08 00:07:11.969 [info] <0.33.0> Application ranch started on node rabbit@f82e877572f0
2018-02-08 00:07:11.969 [info] <0.33.0> Application ranch_proxy_protocol started on node rabbit@f82e877572f0
2018-02-08 00:07:11.971 [info] <0.33.0> Application cowboy started on node rabbit@f82e877572f0
2018-02-08 00:07:11.972 [info] <0.33.0> Application rabbit_common started on node rabbit@f82e877572f0
2018-02-08 00:07:11.981 [info] <0.189.0> 
 Starting RabbitMQ 3.7.3 on Erlang 20.1.7
 Copyright (C) 2007-2018 Pivotal Software, Inc.
 Licensed under the MPL.  See http://www.rabbitmq.com/

  ##  ##
  ##  ##      RabbitMQ 3.7.3. Copyright (C) 2007-2018 Pivotal Software, Inc.
  ##########  Licensed under the MPL.  See http://www.rabbitmq.com/
  ######  ##
  ##########  Logs: <stdout>

              Starting broker...
2018-02-08 00:07:11.998 [info] <0.189.0> 
 node           : rabbit@f82e877572f0
 home dir       : /var/lib/rabbitmq
 config file(s) : /etc/rabbitmq/rabbitmq.conf
 cookie hash    : Ukbm7Ry/10y/+LzhxqS8zg==
 log(s)         : <stdout>
 database dir   : /var/lib/rabbitmq/mnesia/rabbit@f82e877572f0
2018-02-08 00:07:14.244 [info] <0.197.0> Memory high watermark set to 200 MiB (209715200 bytes) of 500 MiB (524288000 bytes) total
2018-02-08 00:07:14.253 [info] <0.199.0> Enabling free disk space monitoring
2018-02-08 00:07:14.253 [info] <0.199.0> Disk free limit set to 50MB
2018-02-08 00:07:14.259 [info] <0.201.0> Limiting to approx 1048476 file handles (943626 sockets)
2018-02-08 00:07:14.259 [info] <0.202.0> FHC read buffering:  OFF
2018-02-08 00:07:14.259 [info] <0.202.0> FHC write buffering: ON
2018-02-08 00:07:14.261 [info] <0.189.0> Node database directory at /var/lib/rabbitmq/mnesia/rabbit@f82e877572f0 is empty. Assuming we need to join an existing cluster or initialise from scratch...
2018-02-08 00:07:14.261 [info] <0.189.0> Configured peer discovery backend: rabbit_peer_discovery_classic_config
2018-02-08 00:07:14.261 [info] <0.189.0> Will try to lock with peer discovery backend rabbit_peer_discovery_classic_config
2018-02-08 00:07:14.262 [info] <0.189.0> Peer discovery backend rabbit_peer_discovery_classic_config does not support registration, skipping randomized startup delay.
2018-02-08 00:07:14.262 [info] <0.189.0> All discovered existing cluster peers: 
2018-02-08 00:07:14.262 [info] <0.189.0> Discovered no peer nodes to cluster with
2018-02-08 00:07:14.267 [info] <0.33.0> Application mnesia exited with reason: stopped
2018-02-08 00:07:14.378 [info] <0.33.0> Application mnesia started on node rabbit@f82e877572f0
2018-02-08 00:07:15.540 [info] <0.189.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
2018-02-08 00:07:15.630 [info] <0.189.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
2018-02-08 00:07:15.747 [info] <0.189.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
2018-02-08 00:07:15.747 [info] <0.189.0> Peer discovery backend rabbit_peer_discovery_classic_config does not support registration, skipping registration.
2018-02-08 00:07:15.748 [info] <0.189.0> Priority queues enabled, real BQ is rabbit_variable_queue
2018-02-08 00:07:15.790 [info] <0.374.0> Starting rabbit_node_monitor
2018-02-08 00:07:15.824 [info] <0.189.0> message_store upgrades: 1 to apply
2018-02-08 00:07:15.824 [info] <0.189.0> message_store upgrades: Applying rabbit_variable_queue:move_messages_to_vhost_store
2018-02-08 00:07:15.825 [info] <0.189.0> message_store upgrades: No durable queues found. Skipping message store migration
2018-02-08 00:07:15.825 [info] <0.189.0> message_store upgrades: Removing the old message store data
2018-02-08 00:07:15.826 [info] <0.189.0> message_store upgrades: All upgrades applied successfully
2018-02-08 00:07:15.891 [info] <0.189.0> Management plugin: using rates mode 'basic'
2018-02-08 00:07:15.891 [info] <0.189.0> Adding vhost '/'
2018-02-08 00:07:16.233 [info] <0.408.0> Making sure data directory '/var/lib/rabbitmq/mnesia/rabbit@f82e877572f0/msg_stores/vhosts/628WB79CIFDYO9LJI6DKMI09L' for vhost '/' exists
2018-02-08 00:07:16.274 [info] <0.408.0> Starting message stores for vhost '/'
2018-02-08 00:07:16.275 [info] <0.412.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_transient": using rabbit_msg_store_ets_index to provide index
2018-02-08 00:07:16.277 [info] <0.408.0> Started message store of type transient for vhost '/'
2018-02-08 00:07:16.277 [info] <0.415.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent": using rabbit_msg_store_ets_index to provide index
2018-02-08 00:07:16.279 [warning] <0.415.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent": rebuilding indices from scratch
2018-02-08 00:07:16.280 [info] <0.408.0> Started message store of type persistent for vhost '/'
2018-02-08 00:07:16.283 [info] <0.189.0> Creating user 'guest'
2018-02-08 00:07:16.316 [info] <0.189.0> Setting user tags for user 'guest' to [administrator]
2018-02-08 00:07:16.350 [info] <0.189.0> Setting permissions for 'guest' in '/' to '.*', '.*', '.*'
2018-02-08 00:07:16.388 [info] <0.453.0> started TCP Listener on [::]:5672
2018-02-08 00:07:16.435 [info] <0.189.0> Setting up a table for connection tracking on this node: tracked_connection_on_node_rabbit@f82e877572f0
2018-02-08 00:07:16.493 [info] <0.189.0> Setting up a table for per-vhost connection counting on this node: tracked_connection_per_vhost_on_node_rabbit@f82e877572f0
2018-02-08 00:07:16.495 [info] <0.33.0> Application rabbit started on node rabbit@f82e877572f0
2018-02-08 00:07:16.495 [info] <0.33.0> Application amqp_client started on node rabbit@f82e877572f0
2018-02-08 00:07:16.496 [info] <0.33.0> Application rabbitmq_web_dispatch started on node rabbit@f82e877572f0
2018-02-08 00:07:16.503 [info] <0.33.0> Application rabbitmq_management_agent started on node rabbit@f82e877572f0
2018-02-08 00:07:16.539 [info] <0.514.0> Management plugin started. Port: 15672
2018-02-08 00:07:16.539 [info] <0.620.0> Statistics database started.
2018-02-08 00:07:16.540 [info] <0.33.0> Application rabbitmq_management started on node rabbit@f82e877572f0
 completed with 3 plugins.
2018-02-08 00:07:16.743 [info] <0.5.0> Server startup complete; 3 plugins started.
 * rabbitmq_management
 * rabbitmq_management_agent
 * rabbitmq_web_dispatch
```

**Closed by yosifkit** 2018-02-08 00:11 UTC

**Comment by mhaamann** [comment] 2018-03-21 12:16
Just a heads up. Remember to clear the rabbitmq folder/volume. Its not enough to upgrade to the latest image alone.
