### ISSUE TITLE
Unable to configure timezone for logging

### ISSUE THREAD

**Issue by azhuchkov** [docker-library/rabbitmq#436] opened 2020-08-28 07:49 UTC
Tried to pass `TZ` environment variable, but it didn't work due to absence of `tzdata` package.
How to install it:
`# apk add -U tzdata`
Then everything works.

**Comment by wglambert** [comment] 2020-08-28 14:10
`TZ` works, but `tzdata` gets you `/etc/zoneinfo` https://github.com/docker-library/rabbitmq/issues/356#issuecomment-516922987

https://github.com/docker-library/rabbitmq/issues/211
>To minimize image size, it's uncommon for additional related tools (such as git or bash) to be included in Alpine-based images.

**Comment by azhuchkov** [comment] 2020-08-28 15:04
Hm, interesting...
What I've got:
```
$ docker run -d --rm --name rabbit rabbitmq:3.7-alpine
$ docker exec rabbit date
Fri Aug 28 14:58:04 UTC 2020

$ docker run -d --rm --name rabbit -e TZ=CST rabbitmq:3.7-alpine
$ docker exec rabbit date
Fri Aug 28 14:59:28 CST 2020
```
It's the same time despite of TZ change. 

Also it seems that other zones like `Europe/Berlin` are unavailable in the container.

**Comment by wglambert** [comment] 2020-08-28 15:49
Weird, I guess it doesn't fully interpret the `TZ` variable correctly without tzdata. I thought it was just for longform names since it output with the timezone

1MB size difference for tzdata, I don't see why it couldn't be added as it's used for logging similar to https://github.com/docker-library/redis/issues/138, resolved with https://github.com/docker-library/redis/pull/162
```console
$ docker build -t rabbitmq:test - << EOF
FROM rabbitmq:alpine
RUN apk add --no-cache tzdata
ENV TZ="Europe/Berlin"
EOF
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM rabbitmq:alpine
 ---> 47efdf34de4a
Step 2/3 : RUN apk add --no-cache tzdata
 ---> Running in ec15f303cd88
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/1) Installing tzdata (2020a-r0)
Executing busybox-1.31.1-r16.trigger
OK: 12 MiB in 24 packages
Removing intermediate container ec15f303cd88
 ---> 2eeb95bd82b1
Step 3/3 : ENV TZ="Europe/Berlin"
 ---> Running in 1c216f288255
Removing intermediate container 1c216f288255
 ---> ae1c0e9928d0
Successfully built ae1c0e9928d0
Successfully tagged rabbitmq:test

$ docker run -d --rm --name rabbit rabbitmq:test
43f9c293ae24a54a8787dfacaea4256cc9a07cb97e2e15f46172c414770cfbd9

$ docker exec rabbit date
Fri Aug 28 17:41:18 CEST 2020

$ date
Fri Aug 28 15:41:21 UTC 2020

$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED              SIZE
rabbitmq            test                ae1c0e9928d0        About a minute ago   109MB
rabbitmq            alpine              47efdf34de4a        21 hours ago         108MB
```

**Comment by tianon** [comment] 2020-08-28 23:44
Duplicate of #211 :heart:

**Comment by wglambert** [comment] 2020-09-01 19:50
Closing with what was said in the other issue
>To minimize image size, it's uncommon for additional related tools (such as git or bash) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile (see the [alpine image description](https://hub.docker.com/_/alpine/) for examples of how to install packages if you are unfamiliar).

**Closed by wglambert** 2020-09-01 19:50 UTC
Labels: Request, question
