### ISSUE TITLE
Add tzdata package to alpine images to enable timezone (TZ) environment variable

### ISSUE THREAD

**Issue by yasithab** [docker-library/rabbitmq#460] opened 2021-01-22 08:45 UTC
The current alpine images do not have **tzdata** package installed. Therefore, the **TZ** environment variable won't work. If possible, please add the **tzdata** package, so we can change the time zone of the container when necessary.

Docker Instruction: `RUN apk add --no-cache tzdata`

**Comment by wglambert** [comment] 2021-01-22 17:15
Duplicate of https://github.com/docker-library/rabbitmq/issues/211

See also https://github.com/docker-library/rabbitmq/issues/436

**Comment by wglambert** [comment] 2021-03-19 17:17
Closing with what was said in the other issue
>To minimize image size, it's uncommon for additional related tools (such as git or bash) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile (see the [alpine image description](https://hub.docker.com/_/alpine/) for examples of how to install packages if you are unfamiliar).

**Closed by wglambert** 2021-03-19 17:17 UTC
Labels: Request
