### ISSUE TITLE
Failed to start with memory limit and high watermark set

### ISSUE THREAD

**Issue by mirasrael** [docker-library/rabbitmq#220] opened 2017-12-13 12:45 UTC
Fails with this error:
```
/usr/local/bin/docker-entrypoint.sh: line 285: :#: command not found
```
I checked this file and it contains (note colon at line start):
```
:# TODO: ...
```
It looks like miss type from vim :)

https://github.com/docker-library/rabbitmq/blob/301c52ad6d75075aa8b42b0977e4f54866c0af96/3.7/docker-entrypoint.sh#L285

**Comment by Tomateauketchup** [comment] 2017-12-13 15:35
Yes i have exactly the same problem :-p

**Comment by tianon** [comment] 2017-12-13 16:29
Duplicate of #215

**Closed by tianon** 2017-12-13 16:29 UTC
