### ISSUE TITLE
docker-compose down data lost?

### ISSUE THREAD

**Issue by im-zhangxi** [docker-library/rabbitmq#395] opened 2020-03-13 04:32 UTC
docker-compose

```
rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: rabbitmq
    restart: always
    ports:
      - "${RABBITMQ_HOST_PORT_C}:5672"
      - "${RABBITMQ_HOST_PORT_S}:15672"
    volumes:
      - ${DATA_DIR}/rabbitmq:/var/lib/rabbitmq:rw
      - ${RABBITMQ_LOG_DIR}:/var/log/rabbitmq:rw
    environment:
       TZ: "$TZ"
       RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
       RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    networks:
          - default
```

When I perform docker-compose down and up, data lost.  help me

**Comment by tianon** [comment] 2020-03-13 06:57
You need to set a `hostname:` value -- if you check `${DATA_DIR}/rabbitmq`, you'll likely see multiple directories for the random hostnames your containers have had.

(Duplicate of #392, most recently.)

**Closed by tianon** 2020-03-13 06:57 UTC
