### ISSUE TITLE
Dependency on Microsoft.Diagnostics.Tracing.EventSource, Version=1.1.28.0

### ISSUE THREAD

**Issue by hanimv** [docker-library/rabbitmq#333] opened 2019-04-04 14:00 UTC
Hi Team,

I am getting following error. I didnt have any problem while using rabbitmq dot net client. This is happening only when I use docker. 

> System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Microsoft.Diagnostics.Tracing.EventSource, Version=1.1.28.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
  Source=RabbitMQ.Client
  StackTrace:
   at RabbitMQ.Client.ESLog.Error(String message, Exception ex)
   at RabbitMQ.Client.Framing.Impl.Connection.LogCloseError(String error, Exception ex)
   at RabbitMQ.Client.Framing.Impl.Connection.HandleMainLoopException(ShutdownEventArgs reason)
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by wglambert** [comment] 2019-04-04 16:28
Linux Containers on Windows doesn't support RabbitMQ https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers#bind-mounts

>These applications all require volume mapping and will not start or run correctly.
>. . .
>RabbitMQ

There's an experimental Dockerfile here https://github.com/docker-library/rabbitmq/issues/168#issuecomment-459916001

And someone using Docker for Windows says he got it to work on the latest version https://github.com/docker-library/rabbitmq/issues/325#issuecomment-470879010

Closing as a duplicate of https://github.com/docker-library/rabbitmq/issues/168 and https://github.com/docker-library/rabbitmq/issues/257

**Closed by wglambert** 2019-04-04 16:28 UTC

**Comment by michaelklishin** [comment] 2019-04-30 11:47
The exception above looks like https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/640 and not an issue with volume mapping.
