### ISSUE TITLE
Cannot set TimeZone

### ISSUE THREAD

**Issue by MrAliev** [docker-library/rabbitmq#557] opened 2022-04-26 07:00 UTC
How can I set a time zone when running an image in docker? 
Setting the environment variable in "docker-compose.yml" file
```
rabbitmq:
    image: masstransit/rabbitmq
    environment:
      TZ: 'Europe/Berlin'
...
```
does not lead to the desired result

**Comment by michaelklishin** [comment] 2022-04-26 09:58
First of all, this image is not `masstransit/rabbitmq`, and we cannot assume how much it overrides or changes there. So you are asking this in the wrong place.

Duplicate of #436, #447, #460.

Consider using GitHub Discussions instead of issues for questions in the future.

**Comment by michaelklishin** [comment] 2022-04-26 10:07
FTR, `masstransit/rabbitmq` [uses the Alpine version](https://github.com/MassTransit/docker-rabbitmq/blob/master/Dockerfile) of this image and installs a community plugin on top.

**Closed** 2022-04-26 21:52 UTC
Labels: question
